---
kind: pipeline
name: default

steps:
  - name: test2.7
    image: python:2.7-alpine
    pull: always
    commands:
      - apk add --no-cache openssl-dev libffi-dev build-base
      - pip install --upgrade pip setuptools wheel -q
      - pip install -r test-requirements.txt -q
      - flake8 ansibleroler
      - pip install -e . -q
      - pytest --cov=ansibleroler tests/ -v
    when:
      event:
        - push
        - tag

  - name: test3.4
    image: python:3.4-alpine
    pull: always
    commands:
      - apk add --no-cache openssl-dev libffi-dev build-base
      - pip install --upgrade pip setuptools wheel -q
      - pip install -r test-requirements.txt -q
      - flake8 ansibleroler
      - pip install -e . -q
      - pytest --cov=ansibleroler tests/ -v
    when:
      event:
        - push
        - tag

  - name: test3.6
    image: python:3.6-alpine
    pull: always
    commands:
      - apk add --no-cache openssl-dev libffi-dev build-base
      - pip install --upgrade pip setuptools wheel -q
      - pip install -r test-requirements.txt -q
      - flake8 ansibleroler
      - pip install -e . -q
      - pytest --cov=ansibleroler tests/ -v
    when:
      event:
        - push
        - tag

  - name: test3.7
    image: python:3.7-alpine
    pull: always
    commands:
      - apk add --no-cache openssl-dev libffi-dev build-base
      - pip install --upgrade pip setuptools wheel -q
      - pip install -r test-requirements.txt -q
      - flake8 ansibleroler
      - pip install -e . -q
      - pytest --cov=ansibleroler tests/ -v
    when:
      event:
        - push
        - tag

  - name: build
    image: python:3.7-alpine
    pull: always
    commands:
      - python setup.py sdist bdist_wheel
    when:
      event:
        - push
        - tag
    depends_on:
      - test2.7
      - test3.4
      - test3.6
      - test3.7

  - name: checksum
    image: alpine
    pull: always
    commands:
      - apk add --no-cache coreutils
      # exclude files
      # - sha256sum -b files/!(*.out) > CHECKSUMFILE
      - sha256sum -b dist/* > dist/sha256sum.txt
    when:
      event:
        - push
        - tag
    depends_on:
      - test2.7
      - test3.4
      - test3.6
      - test3.7

  - name: gpg-sign
    image: plugins/gpgsign:1
    pull: always
    settings:
      key:
        from_secret: gpgsign_key
      passphrase:
        from_secret: gpgsign_passphrase
      detach_sign: true
      files:
        - dist/*
      excludes:
        - dist/sha256sum.txt
    when:
      event:
        - push
        - tag
    depends_on:
      - test2.7
      - test3.4
      - test3.6
      - test3.7

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
    when:
      event:
        - tag
    depends_on:
      - test2.7
      - test3.4
      - test3.6
      - test3.7

  - name: pypi_publish
    image: xoxys/drone-pypi:0.1.0
    pull: always
    settings:
      username:
        from_secret: pypi_username
      password:
        from_secret: pypi_password
      repository: https://upload.pypi.org/legacy/
      skip_build: true
    when:
      event:
        - tag
    depends_on:
      - test2.7
      - test3.4
      - test3.6
      - test3.7
