---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s: %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    ansibleroler:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console]
...
